// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrickcalServer.Data;

#nullable disable

namespace TrickcalServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrickcalServer.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseAtk")
                        .HasColumnType("integer");

                    b.Property<int>("BaseDef")
                        .HasColumnType("integer");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tribe")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseAtk = 120,
                            BaseDef = 80,
                            Class = "전사",
                            Grade = "Star1",
                            Name = "리나",
                            Tribe = "인간"
                        },
                        new
                        {
                            Id = 2,
                            BaseAtk = 110,
                            BaseDef = 70,
                            Class = "궁수",
                            Grade = "Star1",
                            Name = "코볼",
                            Tribe = "수인"
                        },
                        new
                        {
                            Id = 3,
                            BaseAtk = 130,
                            BaseDef = 60,
                            Class = "마법사",
                            Grade = "Star1",
                            Name = "미란다",
                            Tribe = "엘프"
                        },
                        new
                        {
                            Id = 4,
                            BaseAtk = 90,
                            BaseDef = 140,
                            Class = "탱커",
                            Grade = "Star1",
                            Name = "톤즈",
                            Tribe = "기계"
                        },
                        new
                        {
                            Id = 5,
                            BaseAtk = 80,
                            BaseDef = 90,
                            Class = "힐러",
                            Grade = "Star1",
                            Name = "피넛",
                            Tribe = "수인"
                        },
                        new
                        {
                            Id = 6,
                            BaseAtk = 140,
                            BaseDef = 50,
                            Class = "암살자",
                            Grade = "Star1",
                            Name = "쿠로",
                            Tribe = "마족"
                        },
                        new
                        {
                            Id = 7,
                            BaseAtk = 115,
                            BaseDef = 75,
                            Class = "궁수",
                            Grade = "Star1",
                            Name = "도트",
                            Tribe = "인간"
                        },
                        new
                        {
                            Id = 8,
                            BaseAtk = 125,
                            BaseDef = 65,
                            Class = "마법사",
                            Grade = "Star1",
                            Name = "모스",
                            Tribe = "정령"
                        },
                        new
                        {
                            Id = 9,
                            BaseAtk = 118,
                            BaseDef = 85,
                            Class = "전사",
                            Grade = "Star1",
                            Name = "버키",
                            Tribe = "기계"
                        },
                        new
                        {
                            Id = 10,
                            BaseAtk = 85,
                            BaseDef = 95,
                            Class = "힐러",
                            Grade = "Star1",
                            Name = "릴리",
                            Tribe = "엘프"
                        },
                        new
                        {
                            Id = 11,
                            BaseAtk = 200,
                            BaseDef = 120,
                            Class = "마법사",
                            Grade = "Star2",
                            Name = "세라핀",
                            Tribe = "엘프"
                        },
                        new
                        {
                            Id = 12,
                            BaseAtk = 210,
                            BaseDef = 150,
                            Class = "전사",
                            Grade = "Star2",
                            Name = "카이론",
                            Tribe = "수인"
                        },
                        new
                        {
                            Id = 13,
                            BaseAtk = 190,
                            BaseDef = 110,
                            Class = "궁수",
                            Grade = "Star2",
                            Name = "노바",
                            Tribe = "기계"
                        },
                        new
                        {
                            Id = 14,
                            BaseAtk = 160,
                            BaseDef = 220,
                            Class = "탱커",
                            Grade = "Star2",
                            Name = "루시안",
                            Tribe = "인간"
                        },
                        new
                        {
                            Id = 15,
                            BaseAtk = 150,
                            BaseDef = 180,
                            Class = "힐러",
                            Grade = "Star2",
                            Name = "유키",
                            Tribe = "정령"
                        },
                        new
                        {
                            Id = 16,
                            BaseAtk = 230,
                            BaseDef = 100,
                            Class = "암살자",
                            Grade = "Star2",
                            Name = "아스카",
                            Tribe = "마족"
                        },
                        new
                        {
                            Id = 17,
                            BaseAtk = 350,
                            BaseDef = 200,
                            Class = "궁수",
                            Grade = "Star3",
                            Name = "아르테미스",
                            Tribe = "엘프"
                        },
                        new
                        {
                            Id = 18,
                            BaseAtk = 380,
                            BaseDef = 250,
                            Class = "전사",
                            Grade = "Star3",
                            Name = "발키리",
                            Tribe = "인간"
                        },
                        new
                        {
                            Id = 19,
                            BaseAtk = 400,
                            BaseDef = 180,
                            Class = "마법사",
                            Grade = "Star3",
                            Name = "오르페우스",
                            Tribe = "정령"
                        },
                        new
                        {
                            Id = 20,
                            BaseAtk = 500,
                            BaseDef = 350,
                            Class = "지배자",
                            Grade = "Eldain",
                            Name = "엘다인",
                            Tribe = "신족"
                        });
                });

            modelBuilder.Entity("TrickcalServer.Models.GachaBanner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPickupEldain")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PickupCardId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PickupRate")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PickupCardId");

                    b.ToTable("GachaBanners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsPickupEldain = false,
                            Name = "신규 사도 픽업",
                            PickupCardId = 18,
                            PickupRate = 0.008m,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsPickupEldain = true,
                            Name = "엘다인 특별 픽업",
                            PickupCardId = 20,
                            PickupRate = 0.006m,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TrickcalServer.Models.PlayerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Exp")
                        .HasColumnType("bigint");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TrickcalServer.Models.PlayerCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Exp")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Star")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "CharacterId")
                        .IsUnique();

                    b.ToTable("PlayerCharacters");
                });

            modelBuilder.Entity("TrickcalServer.Models.UserCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId", "CardId")
                        .IsUnique();

                    b.ToTable("UserCards");
                });

            modelBuilder.Entity("TrickcalServer.Models.UserCurrency", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Eleaf")
                        .HasColumnType("integer");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("UserCurrencies");

                    b.HasData(
                        new
                        {
                            UserId = "testuser",
                            Eleaf = 10000,
                            Gold = 5000
                        });
                });

            modelBuilder.Entity("TrickcalServer.Models.UserPity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Faith")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("UserPities");

                    b.HasData(
                        new
                        {
                            UserId = "testuser",
                            Faith = 0
                        });
                });

            modelBuilder.Entity("TrickcalServer.Models.GachaBanner", b =>
                {
                    b.HasOne("TrickcalServer.Models.Card", "PickupCard")
                        .WithMany()
                        .HasForeignKey("PickupCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PickupCard");
                });

            modelBuilder.Entity("TrickcalServer.Models.PlayerCharacter", b =>
                {
                    b.HasOne("TrickcalServer.Models.PlayerAccount", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TrickcalServer.Models.UserCard", b =>
                {
                    b.HasOne("TrickcalServer.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("TrickcalServer.Models.PlayerAccount", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
